import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';
import{registerLicense} from'@syncfusion/ej2-base';
import { AppModule } from './app/app.module';
import { enableProdMode } from '@angular/core';


// Registering Syncfusion license key
registerLicense('Mgo+DSMBaFt+QHFqVkNrWk5FaV1CX2BZd1l2QWlaeU4QCV5EYF5SRHNfQV1nSn1Qd0NqWn4=;Mgo+DSMBPh8sVXJ1S0d+X1RPcEBDQmFJfFBmTGlZe1RzckUmHVdTRHRcQlhjSn5XdUZgWHhfdXU=;ORg4AjUWIQA/Gnt2VFhhQlJBfVldXHxLflF1VWpTf1p6d1NWACFaRnZdQV1mSX1TckZgWn5Zc3dU;MTkwNDE3M0AzMjMxMmUzMTJlMzMzNVlKaHc4TG5CWWo0Z2JUSjdMelhnS3ZkRllmbmFoSTM3RERSL2pYTUFPbXM9;MTkwNDE3NEAzMjMxMmUzMTJlMzMzNW9SdDM1amJxK0trTjFiaDJtai9rVzVQWkRPMDlKeFhER2pJNENhc0FjK1k9;NRAiBiAaIQQuGjN/V0d+XU9Hc1REQmJWfFN0RnNQdV50flZAcDwsT3RfQF5jTH5QdkFgWnxfeHRXRw==;MTkwNDE3NkAzMjMxMmUzMTJlMzMzNVo1ZkdJaTZTK05jNHhXQkk2Q1JLblpoWmdrS095d09sT3pDeCt6aUZrQ0E9;MTkwNDE3N0AzMjMxMmUzMTJlMzMzNUFIK0dCNDVhbUN5QmhQYy9wVjY0eDV1UzFsRUZ0VzdRSk9UYkFPWUNrRWc9;Mgo+DSMBMAY9C3t2VFhhQlJBfVldXHxLflF1VWpTf1p6d1NWACFaRnZdQV1mSX1TckZgWn5XdXJS;MTkwNDE3OUAzMjMxMmUzMTJlMzMzNUU3bUxYbUxNM0pKWDZmVXdRaG5vYUpKQjZOK29VSG84VVF6eDR3VWZTdTg9;MTkwNDE4MEAzMjMxMmUzMTJlMzMzNVlYSmVLeUsrVzFYWkJJeXVReEZGcUovQU91OUxacmZmTUVHeE9KUTloZVk9;MTkwNDE4MUAzMjMxMmUzMTJlMzMzNVo1ZkdJaTZTK05jNHhXQkk2Q1JLblpoWmdrS095d09sT3pDeCt6aUZrQ0E9');


enableProdMode()

platformBrowserDynamic().bootstrapModule(AppModule)
  .catch(err => console.error(err));
